# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "operations" branch
  push:
    branches: ["operations"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      # Setup R environment
      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse 
            any::gt

      - name: Install rmarkdown package
        run: Rscript -e "install.packages('rmarkdown')"   
        
      - name: Check rmarkdown package version
        run: Rscript -e "packageVersion('rmarkdown')"

      - name: Install rmarkdown package
        run: Rscript -e "install.packages('lubridate')"   
        
      - name: Check rmarkdown package version
        run: Rscript -e "packageVersion('lubridate')"
        
        # Setup Quarto
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      # Render and Publish
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
